import type { NextPage } from "next";
import Head from "next/head";
import { useReducer } from "react";
import { Prefectures } from "../components/Prefecture";
import { Chart } from "../components/Chart";
import { SeriesContext, SeriesDispatchContext } from "../context";

import styles from "../styles/Home.module.css";
import { seriesReducer } from "../utils/reducer";

const Home: NextPage = () => {
  const [state, dispach] = useReducer(seriesReducer, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>人口グラフ</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <SeriesContext.Provider value={state}>
        <SeriesDispatchContext.Provider value={dispach}>
          <main className={styles.main}>
            <Prefectures />
            <Chart />
          </main>
        </SeriesDispatchContext.Provider>
      </SeriesContext.Provider>
    </div>
  );
};

export default Home;
